"""
Django settings for eshop project.
 
Generated by 'django-admin startproject' using Django 6.0.4.
 
For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
 
from pathlib import Path
 
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
 
load_dotenv()
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-22r=$w-^8p6%(vlkopze)%t4tz17ycg6xght@70w4jtb4z&_u='
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'
 
ALLOWED_HOSTS = ['.vercel.app','localhost','127.0.0.1']
 
 
# Application definition 
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'store',
    'cart',
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'eshop.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]
 
WSGI_APPLICATION = 'eshop.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
db_url = os.getenv('DATABASE_URL')
 
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True
    )
}
 
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',   
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
 
LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'UTC'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
 
STATIC_URL = '/static/'
# STATIC_DIRS нь хөгжүүлэлтийн үед ашиглагдах статик файлуудын байршлыг зааж өгдөг.
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATIC_ROOT нь цуглуулсан статик файлуудыг хадгалах байршлыг зааж өгдөг.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Whitenoise-ийг статик файлуудыг цуглуулах үед ашиглах хадгалах классыг зааж өгнө. 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')